version: '3.8'

services:
  # Backend LiteERP (Spring Boot) - TESTE LOCAL
  liteerp-backend:
    image: vitorhugoms/lite-erp-backend:latest
    container_name: liteerp-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Configurar DATABASE_URL para apontar para seu banco de dados externo
      DATABASE_URL: ${DATABASE_URL:-jdbc:postgresql://host.docker.internal:5432/LiteERP}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-1804}
      JWT_SECRET: ${JWT_SECRET:-seguranca-top-local}
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - lite-erp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  lite-erp-network:
    driver: bridge
